### ISSUE TITLE
org.apache.shiro.config.ConfigurationException: Shiro INI configuration was either not found or discovered to be empty/unconfigured.

### ISSUE THREAD

**Issue by TonyYule** [wukonggg/mz-g#3]
[2016-08-15 04:42:01,584] Artifact mz-gallery:war: Artifact is being deployed, please wait...
15-Aug-2016 16:42:04.109 INFO [RMI TCP Connection(3)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Log4j: 16:42:04 INFO  org.apache.shiro.web.env.EnvironmentLoader [initEnvironment] - Starting Shiro environment initialization.
Log4j: 16:42:04 ERROR org.apache.shiro.web.env.EnvironmentLoader [initEnvironment] - Shiro environment initialization failed
org.apache.shiro.config.ConfigurationException: Shiro INI configuration was either not found or discovered to be empty/unconfigured.
	at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:87)
	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:45)
	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:40)
	at org.apache.shiro.web.env.EnvironmentLoader.createEnvironment(EnvironmentLoader.java:221)
	at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:133)
	at org.apache.shiro.web.env.EnvironmentLoaderListener.contextInitialized(EnvironmentLoaderListener.java:58)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)

**Comment by wukonggg** [comment]
shiro暂时去掉了
